### PR TITLE
Just a couple of minor changes made on the way to publish this library on hex.pm

### PR DESCRIPTION
**Pull request by elbrujohalcon**
- rocked the project with [elvis](http://elvis.inakalabs.com)
- added 2 apps to reduce the number of warnings in the plt
- added changelog
- published the project on [hex.pm](http://hex.pm/packages/inaka_aleppo).

If you want to publish aleppo yourself on hex.pm as http://hex.pm/packages/aleppo, we'll be happy to remove inaka_aleppo from there and just use your package.

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
The only non-decorative non-documentative change is f30c9daeaa83888abdb2622f249066c886cc0a62

**Comment by danikp** [comment]
it will be great if you will split you PR to few, one per issue fixed

**Comment by elbrujohalcon** [comment]
Sorry, @danikp but that's very unlikely to happen anytime soon.

For starters, we do need all the updates at once (particularly for [katana-code](http://github.com/inaka/katana-code) and [elvis](http://github.com/inaka/elvis_core).

On the other hand, it would take time to determine what changes impact what others, it's not just grouping commits into PRs.

Feel free to just close this PR. In that case, we'll keep our branch on [hex](https://hex.pm/packages/inaka_aleppo) and we'll keep using it for our projects.

**Comment by elbrujohalcon** [comment]
This PR is a bit old, I think I'll just close it :trollface:

**Pull request closed without merging**
