### PR TITLE
Hexify

### LINKED ISSUE #16: Please provide a hex package for aleppo
It would be wonderful if a hex package for aleppo would be available. Since there are no dependencies it should be really easy :)

### PR DESCRIPTION
**Pull request by Licenser**
Hi I've published aleppo as a hex package, this are the changes necessary to make it hex-able with riak3. Since it is your project it would be great if you'd take over the package, for that you can ask hex.pm to change ownership, until then I'll try to keep it up to date with the latest tagged release.

For the meantime I added myself as a secondary maintainer so that people having questions regarding the package don't bother you, please remove that if you take over the package since I don't want to claim your work as mine.

Note that this also moves the build tool to rebar3.

This mostly closes #16 .

### CODE REVIEW

**Comment by danikp** [comment]
I will check if your changes (including move to rebar3) will not break CB and if it's ok, will merge it.

**Comment by Licenser** [comment]
awesome :)

**Comment by danikp** [comment]
A time has come. Released new version 0.9.1, but unable to add it because you are the owner.
please add chicagoboss.org@gmail.com as an owner for this package

**Comment by danikp** [comment]
fixed in v0.9.1

**Pull request closed without merging**
